name: Auto Post
on:
  schedule:
    - cron: " * * * * *"
  workflow_dispatch:
jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Coze Workflow
      run: |
        curl -X POST "https://api.coze.com/v1/workflow/stream_run" \
        -H "Authorization: Bearer pat_zpkck81ZDh7AGnqgnb0DQp3t2kdnvDn8h3ss71r5LWcXnFlTsS9LJGxaqgj2yYeH" \
        -H "Content-Type: application/json" \
        -d '{}'
