name: Auto Post
on:
  schedule:
    - cron: " * * * * *"
  workflow_dispatch:
jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Coze Workflow
      run: curl -X POST 'https://api.coze.com/v1/workflow/stream_run' -H 'Authorization: Bearer pat_zpck812Dh7AGnghbBDQp3J2dmvDnh8bs3s7r1SLWcXnF1TS59LXGjaqq3Jy9eH' -H 'Content-Type: application/json' -d '{}'
